# Generated by Django 3.2.3 on 2021-05-18 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddata',
            options={'verbose_name_plural': 'CalorieMeter'},
        ),
    ]
